title: Chris's Blog
paginate: 5

module:
  imports:
    - path: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  displayFullLangName: true
  env: production
  title: Chris's Blog
  keywords: [Blog, Homelab, Linux]
  author: "Chris"
  DateFormat: "2 Jan 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    disableHLJS: true

  label:
    text: "Chris's Blog"

  socialIcons:
    - name: GitHub
      url: "https://github.com/chramb"
    - name: RSS
      url: "index.xml"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # for search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

languages:
  en:
    languageName: ":uk:"
    languageAltTitle: "English (English)"

    description: "My blog in which I write about tech stuff and whatever else I find interesing"
    homeInfoParams:
      Title: "Hi there \U0001F44B"
      Content: Welcome to my blog, I hope you enjoy your stay.
    menu:
      main:
        - identifier: search
          name: Search
          url: /search/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: archive
          name: Posts
          url: /archives/
          weight: 30
        - identifier: about
          name: About
          url: /about/
          weight: 40
  pl:
    author: "Krzysztof"
    languageName: ":poland:"
    languageAltTitle: "Polski (Polish)"
    description: "My blog in which I write about tech stuff and whatever else I find interesing"
    homeInfoParams:
      Title: "Hej \U0001F44B"
      Content: Witaj na moim blogu.
    menu:
      main:
        - identifier: search
          name: Szukaj
          url: /search/
          weight: 10
        - identifier: tags
          name: Tagi
          url: /tags/
          weight: 20
        - identifier: about
          name: O mnie
          url: /about/
          weight: 40
        - identifier: archives
          name: Wpisy
          url: /archives/
          weight: 30
  ru:
    languageName: " " # ":ru"
    languageAltTitle: "Русский (Russian)"
    homeInfoParams:
      Title: "404 Не Найдено"
  es:
    languageName: " " # ":es:"
    languageAltTitle: "Español (Spanish)"
    homeInfoParams:
      Title: "404 No encontrado"

pygmentsUseClasses: true
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    noClasses: false
    style: monokai
