baseURL: "/"
title: Chris's Blog
paginate: 5

module:
  imports:
    - path: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: Chris's Blog
  description: "My blog in which I write about tech stuff and whatever else I find interesing"
  keywords: [Blog, Homelab, Linux]
  author: "Chris"
  DateFormat: "2 Jan 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    disableHLJS: true

  label:
    text: "Chris's Blog"

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog, I hope you enjoy your stay.

  socialIcons:
    - name: GitHub
      url: "https://github.com/chramb"
    - name: RSS
      url: "index.xml"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # for search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

languages:
  en:
    languageName: "English"
    menu:
      main:
        - identifier: search
          name: Search
          url: search/
          weight: 10
        - identifier: tags
          name: Tags
          url: tags/
          weight: 30
        - identifier: about
          name: About
          url: about/
          weight: 40

pygmentsUseClasses: true
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    noClasses: false
    style: monokai
